### ISSUE TITLE
Overall Layout

### ISSUE THREAD

**Issue by Ankurakjain** [it-craftsman/ringsandkisses#10]
Hi everyone, 

We have updated all the pages. Please check and let us know if anything is missing or not working. 

best regards,
Ankur

**Comment by Chralt98** [comment]
Overall, I think that the website is very successful for you. The blue hyperlinks on the start page still bother me a bit and our pictures are still missing in "Our Team", which we can insert ourselves in the production. Great job! This version has been approved.
