### ISSUE TITLE
Overall layout

### ISSUE THREAD

**Issue by Chralt98** [it-craftsman/ringsandkisses#4]
Hey,

the first visible version of the website is already a decent achievement for the current state of development. The header color could be changed from pink to white. 
Has the camera itself been created using SVG? 
The navigation bar shows the borders of the underlying elements with semi-transparency, an unsightly effect. The navigation bar should not necessarily be transparent if underlying objects are more dominant in color. 

The blurry view of the text elements suggests that the website has not yet fully loaded, which should be avoided. In addition, the text is framed and overlaps with the frame. Does the frame have to be black, can't it be a background that turns gray when the mouse moves over it? Please work with our given pictures on the main page, so that the pictures bring color into white.

**Comment by galois26** [comment]
Hi,
Correct, the Logo was created fully using SVG, so we can still amend aspects if required (e.g. if you want the text removed). From your feedback, you liked the first version released but would like some improvements. 
We can work on header colour and improve the navigation bar visibility and transparency issues.I also totally agree with you about the blurry text and that will of course be fixed. We can definitely work on making the text more responsive to improve any layout issues. I think its also a good idea to work with and experiment different border colours to see which works best, especially with a mouse over effect.

Thanks for the feedback.

**Comment by Ankurakjain** [comment]
Hi,
We have made two layouts for you to choose from. The first one you've already seen. The second one is named demo1, whose design you can check. After checking let us know which one suits you best and we can work on it further accordingly.

Waiting for the response!
Ankur

**Comment by Ankurakjain** [comment]
you can check demo1 on this

https://it-craftsman.github.io/ringsandkisses/

**Comment by Chralt98** [comment]
Oh cool! Demo1 layout is better. For additional layout features I will write in another issue.

**Comment by Chralt98** [comment]
cool layout
