### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by galois26** [it-craftsman/ringsandkisses#6]
Current status:
Index.html:
- Waiting for a response from the client in order to decide which layout is preferred, the initial Feature-Layout branch or demo1
- Once confirmed we will work on the changes required.

Current work:
Transform sessions.xml document for html (Adam)
Work on Wedding / Couple photo pages (Adam)
Work on Blog (Ankur)
Work on Contact page (Ankur)

**Comment by it-craftsman** [comment]
The demo1 layout looks best for us. So keep working on the demo1 layout.

**Comment by Chralt98** [comment]
Yeah demo1 is perfectly well.
