### ISSUE TITLE
Website status

### ISSUE THREAD

**Issue by Chralt98** [it-craftsman/ringsandkisses#9]
Hey,

today I clicked on the Home Navigation Bar and noticed that I can not see the required image. I can only see a blank white screen. Could you explain the current status?

Best regards,
Chris

**Comment by Ankurakjain** [comment]
I will check into it. It was working I will see what gets wrong.

**Comment by galois26** [comment]
Would it be possible to check and let us know if there are any errors being produced for the pages build? I think only the repo owner is able to check this currently.

**Comment by it-craftsman** [comment]
Please let me know on which branch the site is located.

**Comment by Ankurakjain** [comment]
The site is located on main branch.

**Comment by Ankurakjain** [comment]
The site is working :+1:

**Comment by Chralt98** [comment]
looks great now!
